CREATE TABLE `bootcamp_class_participant` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bootcamp_class_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `role_id` int(11) NOT NULL,
  `training_status_id` int(11) NOT NULL DEFAULT 1,
  `date_created` datetime NOT NULL,
  `date_not_ready` datetime DEFAULT NULL,
  `date_ready` datetime DEFAULT NULL,
  `date_mandatory` datetime DEFAULT NULL,
  `date_discarded` datetime DEFAULT NULL,
  `date_modified` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `date_deleted` datetime DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `bootcamp_class_id` (`bootcamp_class_id`),
  KEY `user_id` (`user_id`),
  KEY `training_status_id` (`training_status_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `bootcamp_class_participant_ibfk_1` FOREIGN KEY (`bootcamp_class_id`) REFERENCES `bootcamp_class` (`id`),
  CONSTRAINT `bootcamp_class_participant_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
  CONSTRAINT `bootcamp_class_participant_ibfk_3` FOREIGN KEY (`training_status_id`) REFERENCES `training_status` (`id`),
  CONSTRAINT `bootcamp_class_participant_ibfk_4` FOREIGN KEY (`role_id`) REFERENCES `bootcamp_class_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;