CREATE TABLE `squad` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8mb4_czech_ci NOT NULL,
  `squad_type_id` int(11) NOT NULL DEFAULT 2,
  `parent_squad_id` int(11) DEFAULT NULL,
  `detachment_id` int(11) DEFAULT NULL,
  `center_id` int(9) DEFAULT NULL,
  `note` text COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `abbreviation` text COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `is_active` smallint(1) DEFAULT 1,
  `date_created` datetime NOT NULL DEFAULT current_timestamp(),
  `date_deleted` datetime DEFAULT NULL,
  `date_modified` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `created_by` int(11) NOT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `detachment_id` (`detachment_id`),
  KEY `center_id` (`center_id`),
  KEY `squad_type_id` (`squad_type_id`),
  CONSTRAINT `squad_ibfk_1` FOREIGN KEY (`detachment_id`) REFERENCES `detachment` (`id`) ON DELETE CASCADE,
  CONSTRAINT `squad_ibfk_2` FOREIGN KEY (`center_id`) REFERENCES `center` (`id`) ON DELETE CASCADE,
  CONSTRAINT `squad_ibfk_3` FOREIGN KEY (`squad_type_id`) REFERENCES `squad_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;