CREATE TABLE `user` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `nick` varchar(100) COLLATE utf8mb4_czech_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_czech_ci NOT NULL,
  `password` varchar(100) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `discord_id` varchar(64) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `steam_id` varchar(64) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `login_role_id` int(11) NOT NULL DEFAULT 3,
  `date_created` datetime NOT NULL DEFAULT current_timestamp(),
  `date_modified` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `date_deleted` datetime DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `deleted_by` int(9) DEFAULT NULL,
  `note` text COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `squad_id` int(11) DEFAULT NULL,
  `squad_pos` int(9) DEFAULT NULL,
  `rank_id` int(11) NOT NULL DEFAULT 1,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `is_super_admin` tinyint(1) NOT NULL DEFAULT 0,
  `is_commander` tinyint(1) NOT NULL DEFAULT 0,
  `is_instructor` tinyint(1) NOT NULL DEFAULT 0,
  `is_squadleader` tinyint(1) NOT NULL DEFAULT 0,
  `tactical_points` int(9) NOT NULL DEFAULT 0,
  `penalty` int(9) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `date_last_login` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `squad_id` (`squad_id`),
  KEY `rank_id` (`rank_id`),
  KEY `login_role_id` (`login_role_id`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`squad_id`) REFERENCES `squad` (`id`),
  CONSTRAINT `user_ibfk_2` FOREIGN KEY (`rank_id`) REFERENCES `rank` (`id`),
  CONSTRAINT `user_ibfk_3` FOREIGN KEY (`login_role_id`) REFERENCES `login_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;