INSERT INTO `rank` (`id`, `name`) VALUES
(1,	'Vojín'),
(2,	'Svobodník'),
(3,	'Desátnik'),
(4,	'Četař'),
(5,	'Rotný'),
(6,	'Rotmistr'),
(7,	'Praporčík'),
(8,	'Nadpraporčík'),
(9,	'Stábní praporčík'),
(10,	'Nadporučík'),
(11,	'Kapitán'),
(12,	'Major'),
(13,	'Podpluovník'),
(14,	'Plukovník');