INSERT INTO `rank` (`id`, `name`, `created_by`) VALUES
(1,	'Vojín',2),
(2,	'Svobodník',2),
(3,	'Desátnik',2),
(4,	'Četař',2),
(5,	'Rotný',2),
(6,	'Rotmistr',2),
(7,	'Praporčík',2),
(8,	'Nadpraporčík',2),
(9,	'Stábní praporčík',2),
(10,	'Nadporučík',2),
(11,	'Kapitán',2),
(12,	'Major',2),
(13,	'Podpluovník',2),
(14,	'Plukovník',2);